# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SurfTabUI.ui'
#
# Created: Fri Dec 20 20:07:48 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(405, 275)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox_url = QtGui.QGroupBox(Form)
        self.groupBox_url.setGeometry(QtCore.QRect(10, 10, 381, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_url.setFont(font)
        self.groupBox_url.setObjectName(_fromUtf8("groupBox_url"))
        self.widget = QtGui.QWidget(self.groupBox_url)
        self.widget.setGeometry(QtCore.QRect(11, 20, 361, 141))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 6, 0, 6)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_url = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_url.setFont(font)
        self.label_url.setObjectName(_fromUtf8("label_url"))
        self.gridLayout.addWidget(self.label_url, 0, 0, 1, 1)
        self.lineEdit_urlpath = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_urlpath.sizePolicy().hasHeightForWidth())
        self.lineEdit_urlpath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_urlpath.setFont(font)
        self.lineEdit_urlpath.setReadOnly(True)
        self.lineEdit_urlpath.setObjectName(_fromUtf8("lineEdit_urlpath"))
        self.gridLayout.addWidget(self.lineEdit_urlpath, 0, 1, 1, 1)
        self.btn_choose = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose.sizePolicy().hasHeightForWidth())
        self.btn_choose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_choose.setFont(font)
        self.btn_choose.setObjectName(_fromUtf8("btn_choose"))
        self.gridLayout.addWidget(self.btn_choose, 0, 2, 1, 1)
        self.label_user = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_user.setFont(font)
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.gridLayout.addWidget(self.label_user, 1, 0, 1, 1)
        self.lineEdit_user = QtGui.QLineEdit(self.widget)
        self.lineEdit_user.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_user.sizePolicy().hasHeightForWidth())
        self.lineEdit_user.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.gridLayout.addWidget(self.lineEdit_user, 1, 1, 1, 1)
        self.btn_start = QtGui.QPushButton(self.widget)
        self.btn_start.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.gridLayout.addWidget(self.btn_start, 1, 2, 1, 1)
        self.label_pwd = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_pwd.setFont(font)
        self.label_pwd.setObjectName(_fromUtf8("label_pwd"))
        self.gridLayout.addWidget(self.label_pwd, 2, 0, 1, 1)
        self.lineEdit_pwd = QtGui.QLineEdit(self.widget)
        self.lineEdit_pwd.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pwd.sizePolicy().hasHeightForWidth())
        self.lineEdit_pwd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.lineEdit_pwd.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName(_fromUtf8("lineEdit_pwd"))
        self.gridLayout.addWidget(self.lineEdit_pwd, 2, 1, 1, 1)
        self.checkBox_proxy = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_proxy.sizePolicy().hasHeightForWidth())
        self.checkBox_proxy.setSizePolicy(sizePolicy)
        self.checkBox_proxy.setObjectName(_fromUtf8("checkBox_proxy"))
        self.gridLayout.addWidget(self.checkBox_proxy, 2, 2, 1, 1)
        self.gridLayout.setRowMinimumHeight(0, 30)
        self.gridLayout.setRowMinimumHeight(1, 29)
        self.gridLayout.setRowMinimumHeight(2, 30)
        self.groupBox_status = QtGui.QGroupBox(Form)
        self.groupBox_status.setGeometry(QtCore.QRect(10, 190, 381, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.groupBox_status.setFont(font)
        self.groupBox_status.setObjectName(_fromUtf8("groupBox_status"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_status)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 361, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "拨测专用", None))
        self.groupBox_url.setTitle(_translate("Form", "拨测选项", None))
        self.label_url.setText(_translate("Form", "URL地址：", None))
        self.btn_choose.setText(_translate("Form", "选  择..", None))
        self.label_user.setText(_translate("Form", "用户名：", None))
        self.btn_start.setText(_translate("Form", "开始拨测", None))
        self.label_pwd.setText(_translate("Form", "密   码：", None))
        self.checkBox_proxy.setText(_translate("Form", "代理拨测", None))
        self.groupBox_status.setTitle(_translate("Form", "拨测进度", None))

