# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created: Tue Dec 03 16:51:48 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(400, 266)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox_proxy = QtGui.QGroupBox(Form)
        self.groupBox_proxy.setGeometry(QtCore.QRect(20, 89, 361, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_proxy.setFont(font)
        self.groupBox_proxy.setObjectName(_fromUtf8("groupBox_proxy"))
        self.btn_start = QtGui.QPushButton(self.groupBox_proxy)
        self.btn_start.setEnabled(False)
        self.btn_start.setGeometry(QtCore.QRect(270, 20, 75, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.label_user = QtGui.QLabel(self.groupBox_proxy)
        self.label_user.setGeometry(QtCore.QRect(20, 20, 51, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_user.setFont(font)
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.label_pwd = QtGui.QLabel(self.groupBox_proxy)
        self.label_pwd.setGeometry(QtCore.QRect(20, 60, 51, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_pwd.setFont(font)
        self.label_pwd.setObjectName(_fromUtf8("label_pwd"))
        self.lineEdit_pwd = QtGui.QLineEdit(self.groupBox_proxy)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(79, 60, 181, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.lineEdit_pwd.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName(_fromUtf8("lineEdit_pwd"))
        self.lineEdit_user = QtGui.QLineEdit(self.groupBox_proxy)
        self.lineEdit_user.setGeometry(QtCore.QRect(80, 20, 181, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.groupBox_url = QtGui.QGroupBox(Form)
        self.groupBox_url.setGeometry(QtCore.QRect(20, 9, 361, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_url.setFont(font)
        self.groupBox_url.setObjectName(_fromUtf8("groupBox_url"))
        self.btn_choose = QtGui.QPushButton(self.groupBox_url)
        self.btn_choose.setGeometry(QtCore.QRect(270, 20, 75, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_choose.setFont(font)
        self.btn_choose.setObjectName(_fromUtf8("btn_choose"))
        self.label_url = QtGui.QLabel(self.groupBox_url)
        self.label_url.setGeometry(QtCore.QRect(20, 20, 54, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_url.setFont(font)
        self.label_url.setObjectName(_fromUtf8("label_url"))
        self.lineEdit_urlpath = QtGui.QLineEdit(self.groupBox_url)
        self.lineEdit_urlpath.setGeometry(QtCore.QRect(80, 20, 181, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_urlpath.setFont(font)
        self.lineEdit_urlpath.setReadOnly(True)
        self.lineEdit_urlpath.setObjectName(_fromUtf8("lineEdit_urlpath"))
        self.groupBox_status = QtGui.QGroupBox(Form)
        self.groupBox_status.setGeometry(QtCore.QRect(20, 200, 361, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.groupBox_status.setFont(font)
        self.groupBox_status.setObjectName(_fromUtf8("groupBox_status"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_status)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 321, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_user, self.lineEdit_pwd)
        Form.setTabOrder(self.lineEdit_pwd, self.btn_choose)
        Form.setTabOrder(self.btn_choose, self.btn_start)
        Form.setTabOrder(self.btn_start, self.lineEdit_urlpath)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "CATR代理拨测专用", None))
        self.groupBox_proxy.setTitle(_translate("Form", "代理服务器登陆", None))
        self.btn_start.setText(_translate("Form", "开始拨测", None))
        self.label_user.setText(_translate("Form", "用户名：", None))
        self.label_pwd.setText(_translate("Form", "密   码：", None))
        self.groupBox_url.setTitle(_translate("Form", "拨测列表", None))
        self.btn_choose.setText(_translate("Form", "选  择..", None))
        self.label_url.setText(_translate("Form", "URL地址：", None))
        self.groupBox_status.setTitle(_translate("Form", "拨测进度", None))

